---
title: 'Syllabus'
output: 
  html_document:
    toc: false
---

\  

The course will start at 09:30 each morning and finish at 17:00. We will break for a one hour lunch break around 12:30. However, everyone learns R and statistics in their own way and at their own pace so this syllabus should be treated as indicative rather than absolute. There will also be plenty of opportunities to take short breaks during the course.

The live sessions will be held on Blackboard Collaborate at the time indicated in the timetable below. The recorded video lectures will be hosted on MyAberdeen and you should watch them at the time indicated below.

<!--All teaching will be held in room FN113 in the Fraser Noble building (building No. 7 on [this map](images/uoa_map.png){target="_blank"} on the old Aberdeen campus).
-->

\  

#### Monday 17^th^ April 2023

\  

|09:30 - 10:00 | 10:00 - 11:00 | 11:00 - 12:30 | 12:30 - 13:30 |13:30 - 16:00 | 16:00 - 17:00 |
|:------------|:-------------|:-------------|:-------------|:------------|:-------------|
| Course introduction (ALL - live)  | Graphical data exploration (GDE) theory lecture (recorded) | GDE live practical (AD) | LUNCH |GDE live practical, Live review session (AD)| Linear models theory lectures (recorded AD), Linear models paper exercise |

\  

\  

#### Tuesday 18^th^ April 2023 

\  

|09:30 - 11:00      | 11:00 - 12:30     | 12:30 - 13:30 |13:30 - 16:00    | 16:00 - 17:00|
|:---------------------|:-----------------|:-------------|:---------------|:---------------|
|Linear model theory (recorded AD)|Linear models live practical (AD) – single continuous explanatory variable|LUNCH|Linear models live practical (AD) – single continuous explanatory variable, Live review session|Linear models theory – single categorical explanatory variable (recorded AD)|

\  

\  

#### Wednesday 19^th^ April 2023

\  

|09:30 - 11:30               | 11:30 - 12:30     | 12:30 - 13:30 |13:30 - 14:30    | 14:30 - 17:00      |
|:--------------------------|:-----------------|:-------------|:---------------|:------------------|
|Linear models live practical (AD) – single categorical explanatory variable | Linear models review session (AD) – single categorical explanatory variable| LUNCH |Linear models theory - categorical and continuous explanatory variables (recorded AD)| Linear models live practical – models with continuous and categorical explanatory variables|

\  
<!--
#### Thursday 20^th^ April 2023

\  

|09:30 - 12:30               | 12:30 - 13:30 |13:30 - 15:00    | 15:00 - 17:00      |
|:--------------------------|:-------------|:---------------|:------------------|
|Linear models live practical (AD) – categorical and continuous explanatory variable| LUNCH |Live exercise review session (AD)| Linear models theory - model selection (recorded AD)|

\  
-->

#### Friday 21^st^ April 2023

\  

|09:30 - 11:30               | 11:30 - 12:30 |12:30 - 13:30    | 13:30 - 16:30| 16:30 - 17:00|
|:--------------------------|:-------------|:---------------|:---------------|:----------------|
|Linear models live practical (AD) – categorical and continuous explanatory variable|Linear models theory - model selection (recorded AD)| LUNCH | Linear models live practical (AD) – model selection| Course wash-up and close | 

\  

AD – Alex Douglas 

\  
